SET @organization_id = 1;

INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('1','УЧАСТНИК БОЕВЫХ ДЕЙСТВИЙ',@organization_id,'5');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('2','УЧАСТНИК ВОЙНЫ',@organization_id,'10');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('3','ЧЛЕН СЕМЬИ ПОГИБШЕГО/УМЕРШЕГО ВЕТЕРАНА ВОЙНЫ',@organization_id,'21');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('4','ИНВАЛИД ВОЙНЫ ПЕРВОЙ ГРУППЫ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('5','ИНВАЛИД ВОЙНЫ ВТОРОЙ ГРУППЫ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('6','ИНВАЛИД ВОЙНЫ ТРЕТЬЕЙ ГРУППЫ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('7','РЕБЕНОК ВОЙНЫ',@organization_id,'34');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('8','ЛИЦО С ОСОБЫМИ ЗАСЛУГАМИ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('9','РОДИТЕЛИ УМЕРШЕГО ЛИЦА С ОСОБЫМИ ЗАСЛУГАМИ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('10','ВДОВА/ВДОВЕЦ ЛИЦА С ОСОБЫМИ ЗАСЛУГАМИ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('11','ВДОВА/ВДОВЕЦ ЛИЦА С ОСОБЫМИ ТРУДОВЫМИ ЗАСЛУГАМИ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('12','ЛИЦО С ОСОБЫМИ ТРУДОВЫМИ ЗАСЛУГАМИ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('13','РОДИТЕЛИ УМЕРШЕГО ЛИЦА С ОСОБЫМИ ТРУДОВЫМИ ЗАСЛУГАМИ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('16','МНОГОДЕТНЫЕ СЕМЬИ',@organization_id,'22');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('17','ЧЛЕН  МНОГОДЕТНОЙ СЕМЬИ',@organization_id,'22');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('18','ВЕТЕРАН СЛУЖБЫ ГРАЖДАНСКОЙ ЗИЩИТЫ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('19','ВЕТЕРАН ГОСУДАРСТВЕННОЙ КРИМ.-ИСПОЛНИТЕЛЬНОЙ СЛУЖБЫ',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('20','СЕЛЬСКИЙ ПЕДАГОГ НА ПЕНСИИ',@organization_id,'40');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('21','СЕЛЬСКИЙ БИБЛИОТЕКАРЬ НА ПЕНСИИ',@organization_id,'41');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('22','СЕЛЬСКИЙ СПЕЦИАЛИСТ ПО ЗАЩИТЕ РАСТЕНИЙ НА ПЕНСИИ',@organization_id,'45');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('23','СЕЛЬСКИЙ МЕДИК НА ПЕНСИИ',@organization_id,'44');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('24','СУДЬЯ В ОТСТАВКЕ',@organization_id,'12');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('25','СЛЕДОВАТЕЛЬ ПРОКУРАТУРЫ НА ПЕНСИИ',@organization_id,'18');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('26','НАЛОГОВЫЙ МИЛИЦИОНЕР НА ПЕНСИИ',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('27','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО НАЛОГОВОГО МИЛИЦИОНЕРА',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('28','СЕЛЬСКИЙ НАЛОГОВЫЙ МИЛИЦИОНЕР НА ПЕНСИИ',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('29','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ СЕЛЬСКОГО НАЛОГОВОГО МИЛИЦИОНЕРА',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('30','ВОЕННОСЛУЖАЩИЙ СБУ НА ПЕНСИИ',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('31','ЛИЦО (ЧАЭС) - 1 КАТЕГОРИЯ',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('32','ЛИЦО (ЧАЭС) - 2 КАТЕГОРИЯ - ЛИКВИДАТОР',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('33','ЛИЦО (ЧАЭС) - 2 КАТЕГОРИЯ - ПОТЕРПЕВШИЙ',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('34','ЛИЦО (ЧАЭС) - 3 КАТЕГОРИЯ',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('35','ЛИЦО (ЧАЭС) - 4 КАТЕГОРИЯ',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('36','ЖЕНА/МУЖ (ЧАЭС) УМЕРШЕГО ГРАЖДАНИНА',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('37','РЕБЕНОК (ЧАЭС) УМЕРШЕГО ГРАЖДАНИНА',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('38','РЕБЕНОК (ЧАЭС) ПОТЕРПЕВШЕГО',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('39','РЕБЕНОК (ЧАЭС) - ИНВАЛИД',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('40','ЛИЦО (ЧАЭС), РАБОТАВШЕЕ ЗА ПРЕДЕЛАМИ ЗОНЫ ОТЧУЖДЕНИЯ (ЛИКВИДАЦИЯ ПОСЛЕДСТВИЙ АВАРИИ)',@organization_id,'14');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('41','СОТРУДНИК УГОЛОВНО-ИСПОЛНИТЕЛЬНОЙ СИСТЕМЫ НА ПЕНСИИ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('42','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО СОТРУДНИКА УГОЛОВНО-ИСПОЛНИТЕЛЬНОЙ СИСТЕМЫ',@organization_id,'18');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('43','СЕЛЬСКИЙ СОТРУДНИК УГОЛОВНО-ИСПОЛНИТЕЛЬНОЙ СИСТЕМЫ НА ПЕНСИИ',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('44','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО СЕЛЬСКОГО СОТРУДНИКА УГОЛОВНО-ИСПОЛНИТЕЛЬНОЙ СИСТЕМЫ',@organization_id,'21');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('45','МИЛИЦИОНЕР НА ПЕНСИИ',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('46','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО МИЛИЦИОНЕРА',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('47','СЕЛЬСКИЙ МИЛИЦИОНЕР НА ПЕНСИИ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('48','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО СЕЛЬСКОГО МИЛИЦИОНЕРА',@organization_id,'21');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('49','ВЕТЕРАН ВОИНСКОЙ СЛУЖБЫ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('50','ВДОВА/ВДОВЕЦ ВЕТЕРАНА ВОИНСКОЙ СЛУЖБЫ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('51','ЧЛЕН СЕМЬИ ВОЕННОСЛУЖАЩЕГО, ПОГИБШЕГО, УМЕРШЕГО, ПРОПАВШЕГО БЕЗ ВЕСТИ ИЛИ СТАВШЕГО ИНВАЛИДОМ',@organization_id,'21');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('52','РОДИТЕЛИ ВОЕННОСЛУЖАЩЕГО, СТАВШЕГО ИНВАЛИДОМ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('53','ВДОВА/ВДОВЕЦ ВОЕННОСЛУЖАЩЕГО И ЕГО ДЕТИ',@organization_id,'15');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('54','ЖЕНА/МУЖ ВОЕННОСЛУЖАЩЕГО, ПРОПАВШЕГО БЕЗ ВЕСТИ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('55','РОДИТЕЛИ ПОГИБШЕГО ВОЕННОСЛУЖАЩЕГО',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('56','ИНВАЛИД ВОИНСКОЙ СЛУЖБЫ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('57','ВЕТЕРАН ОРГАНОВ ВНУТРЕННИХ ДЕЛ',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('58','ВДОВА/ВДОВЕЦ, ВЕТЕРАНА ОРГАНОВ ВНУТРЕННИХ ДЕЛ',@organization_id,'11');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('59','ПОЖАРНЫЙ НА ПЕНСИИ',@organization_id,'17');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('60','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО ПОЖАРНОГО',@organization_id,'17');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('61','ВЕТЕРАН ГОСУДАРСТВЕННОЙ ПОЖАРНОЙ ОХРАНЫ',@organization_id,'17');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('62','ВДОВА/ВДОВЕЦ ВЕТЕРАНА ГОСУДАРСТВЕННОЙ ПОЖАРНОЙ ОХРАНЫ',@organization_id,'17');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('63','РЕАБИЛИТИРОВАННЫЕ, СТАВШИЕ ИНВАЛИДАМИ ВСЛЕДСТВИИ РЕПРЕССИЙ, ЛИБО ЯВЛЯЮЩИЕСЯ ПЕНСИОНЕРАМИ, ИМЕЮЩИМИ П',@organization_id,'13');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('65','ИНВАЛИД 1 ГРУППЫ ПО ЗРЕНИЮ ИЛИ С ВРАЖДЕННЫМ ОРА',@organization_id,'31');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('66','ИНВАЛИД 2 ГРУППЫ ПО ЗРЕНИЮ ИЛИ С ВРАЖДЕННЫМ ОРА',@organization_id,'31');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('67','ИНВАЛИД 1 ГРУППЫ, КРОМЕ ИНВАЛИДОВ ПО ЗРЕНИЮ ИЛИ С ВРОЖДЕННЫМ ОРА',@organization_id,'2');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('68','ИНВАЛИД 2 ГРУППЫ, КРОМЕ ИНВАЛИДОВ ПО ЗРЕНИЮ ИЛИ С ВРОЖДЕННЫМ ОРА',@organization_id,'2');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('69','ИНВАЛИД 3 ГРУППЫ',@organization_id,'2');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('70','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(1)',@organization_id,'5');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('71','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(2) - ИНВАЛИД 1 ГРУППЫ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('72','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(2) - ИНВАЛИД 2 ГРУППЫ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('73','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(2) - ИНВАЛИД 3 ГРУППЫ',@organization_id,'1');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('74','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(3)',@organization_id,'13');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('75','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(4)',@organization_id,'20');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('80','ВЕТЕРАН ГОСУДАРСТВЕННОЙ СЛУЖБЫ СПЕЦ.СВЯЗИ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('81','ВДОВА/ВДОВЕЦ ВЕТЕРАНА ГОСУДАРСТВЕННОЙ СЛУЖБЫ СПЕЦ.СВЯЗИ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('82','РОДИТЕЛИ И ЧЛЕНЫ СЕМЬИ ПОГИБШЕГО/УМЕРШЕГО СОТРУДНИКА ГОСУДАРСТВЕННОЙ СЛУЖБЫ СПЕЦ.СВЯЗИ',@organization_id,'16');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('83','РОДИТЕЛИ И ЧЛЕНЫ СЕМЬИ СОТРУДНИКА ГРАЖДАНСКОЙ ОБОРОНЫ, ПОГИБШЕГО, УМЕРШЕГО, ПРОПАВШЕГО БЕЗ ВЕСТИ ИЛИ',@organization_id,'15');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('84','МАТЕРИ-ГЕРОИНИ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('85','ДЕТИ-ИНВАЛИДЫ, ПРИКОВАННЫЕ К КРОВАТИ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('86','ДЕТИ-ИНВАЛИДЫ ДО 18 ЛЕТ, ГДЕ ОБА РОДИТЕЛИ ИНВАЛИДЫ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('87','МНОГОДЕТНЫЕ СЕМЬИ (3 И БОЛЕЕ ДЕТЕЙ ДО 18 ЛЕТ)',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('88','МАТЕРИ-ОДИНОЧКИ (2 И БОЛЕЕ ДЕТЕЙ ДО 18 ЛЕТ)',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('89','ДЕТИ-ИНВАЛИДЫ С ОНКОЛОГИЧЕСКИМИ ЗАБОЛЕВАНИЯМИ ДО 18 ЛЕТ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('90','ИНВАЛИДЫ 1 ГРУППЫ, ПОЛУЧАЮЩИЕ СОЦИАЛЬНУЮ ПЕНСИЮ ИЛИ ГОСУДАРСТВЕННУЮ ПОМОЩЬ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('91','НЕРАБОТАЮЩИЕ РОДИТЕЛИ, ОСУЩЕСТВЛЯЮЩИЕ УХОД ЗА РЕБЕНКОМ-ИНВАЛИДОМ ДО 18 ЛЕТ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('92','ИНВАЛИДЫ 1, 2 ГРУППЫ ПО ЗРЕНИЮ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('93','СЕМЬИ ДЕТЕЙ ДО 18 ЛЕТ, БОЛЬНЫХ ДЦП',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('94','ГРАЖДАНЕ, РЕАБИЛИТИРОВАННЫЕ СОГЛАСНО',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('95','СЕМЬИ ПОГИБШИХ (РЯДОВОЙ СОСТАВ) ПРИ ПРОХОЖДЕНИИ СРОЧНОЙ ВОИНСКОЙ СЛУЖБЫ, ИСПОЛНЯВШИХ СВОЙ ДОЛГ В МИ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('96','ПРИЕМНЫЕ СЕМЬИ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('97','ДВОРНИКИ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('98','АВАРИЙНО-ДИСПЕТЧЕРСКАЯ СЛУЖБА',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('99','ПРИЕМНЫЕ СЕМЬИ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('100','СОЦИАЛЬНЫЕ РАБОЧИЕ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('101','УХОД ЗА ИНВАЛИДОМ 1 ГРУППЫ ВОВ',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('102','РАБОТНИКИ ХКП \"ГОРЭЛЕКТРОТРАНС\"',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('103','АФГАНИСТАН',@organization_id,'50');
INSERT INTO `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) VALUES('104','ВЕТЕРАН НАЛОГОВОЙ МИЛИЦИИ',@organization_id,'50');
