package org.complitex.osznconnection.file.service.process;

/**
* @author Anatoly A. Ivanov java@inheaven.ru
*         Date: 13.04.11 18:36
*/
public enum ProcessType {
    LOAD_GROUP,
    BIND_GROUP,
    FILL_GROUP,
    SAVE_GROUP,

    LOAD_ACTUAL_PAYMENT,
    BIND_ACTUAL_PAYMENT,
    FILL_ACTUAL_PAYMENT,
    SAVE_ACTUAL_PAYMENT,
    
    LOAD_SUBSIDY,
    BIND_SUBSIDY,
    FILL_SUBSIDY,
    SAVE_SUBSIDY,
    
    LOAD_DWELLING_CHARACTERISTICS,
    BIND_DWELLING_CHARACTERISTICS,
    FILL_DWELLING_CHARACTERISTICS,
    SAVE_DWELLING_CHARACTERISTICS,
    
    LOAD_FACILITY_SERVICE_TYPE,
    BIND_FACILITY_SERVICE_TYPE,
    FILL_FACILITY_SERVICE_TYPE,
    SAVE_FACILITY_SERVICE_TYPE,
    
    LOAD_FACILITY_STREET_TYPE_REFERENCE,
    LOAD_FACILITY_STREET_REFERENCE,
    LOAD_FACILITY_TARIF_REFERENCE,
    
    FILL_FACILITY_FORM2,
    SAVE_FACILITY_FORM2,

    LOAD_SUBSIDY_TARIF
}
