//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 04:58:15 PM NOVST 
//


package org.complitex.osznconnection.file.service.file_description.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FieldType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="java.lang.String"/>
 *     &lt;enumeration value="java.lang.Integer"/>
 *     &lt;enumeration value="java.math.BigDecimal"/>
 *     &lt;enumeration value="java.util.Date"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FieldType")
@XmlEnum
public enum FieldType {

    @XmlEnumValue("java.lang.String")
    STRING("java.lang.String"),

    @XmlEnumValue("java.lang.Integer")
    INTEGER("java.lang.Integer"),

    @XmlEnumValue("java.lang.Long")
    LONG("java.lang.Long"),

    @XmlEnumValue("java.math.BigDecimal")
    BIG_DECIMAL("java.math.BigDecimal"),

    @XmlEnumValue("java.util.Date")
    DATE("java.util.Date");

    private final String value;

    FieldType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FieldType fromValue(String v) {
        for (FieldType c: FieldType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
