set @organization_id = 1;

insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('176','69','ИНВАЛИД 3 ГРУППЫ',@organization_id,'2');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('163','49','ВЕТЕРАН ВОИНСКОЙ СЛУЖБЫ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('162','48','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО СЕЛЬСКОГО МИЛИЦИОНЕРА',@organization_id,'21');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('161','47','СЕЛЬСКИЙ МИЛИЦИОНЕР НА ПЕНСИИ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('160','44','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО СЕЛЬСКОГО СОТРУДНИКА УГОЛОВНО-ИСПОЛНИТЕЛЬНОЙ СИСТЕМЫ',@organization_id,'21');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('159','43','СЕЛЬСКИЙ СОТРУДНИК УГОЛОВНО-ИСПОЛНИТЕЛЬНОЙ СИСТЕМЫ НА ПЕНСИИ',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('158','42','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО СОТРУДНИКА УГОЛОВНО-ИСПОЛНИТЕЛЬНОЙ СИСТЕМЫ',@organization_id,'18');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('157','39','РЕБЕНОК (ЧАЭС) - ИНВАЛИД',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('156','38','РЕБЕНОК (ЧАЭС) ПОТЕРПЕВШЕГО',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('155','36','ЖЕНА/МУЖ (ЧАЭС) УМЕРШЕГО ГРАЖДАНИНА',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('154','34','ЛИЦО (ЧАЭС) - 3 КАТЕГОРИЯ',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('164','52','РОДИТЕЛИ ВОЕННОСЛУЖАЩЕГО, СТАВШЕГО ИНВАЛИДОМ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('165','53','ВДОВА/ВДОВЕЦ ВОЕННОСЛУЖАЩЕГО И ЕГО ДЕТИ',@organization_id,'15');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('175','68','ИНВАЛИД 2 ГРУППЫ, КРОМЕ ИНВАЛИДОВ ПО ЗРЕНИЮ ИЛИ С ВРОЖДЕННЫМ ОРА',@organization_id,'2');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('174','67','ИНВАЛИД 1 ГРУППЫ, КРОМЕ ИНВАЛИДОВ ПО ЗРЕНИЮ ИЛИ С ВРОЖДЕННЫМ ОРА',@organization_id,'2');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('173','66','ИНВАЛИД 2 ГРУППЫ ПО ЗРЕНИЮ ИЛИ С ВРАЖДЕННЫМ ОРА',@organization_id,'31');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('172','65','ИНВАЛИД 1 ГРУППЫ ПО ЗРЕНИЮ ИЛИ С ВРАЖДЕННЫМ ОРА',@organization_id,'31');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('171','63','РЕАБИЛИТИРОВАННЫЕ, СТАВШИЕ ИНВАЛИДАМИ ВСЛЕДСТВИИ РЕПРЕССИЙ, ЛИБО ЯВЛЯЮЩИЕСЯ ПЕНСИОНЕРАМИ, ИМЕЮЩИМИ П',@organization_id,'13');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('170','60','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО ПОЖАРНОГО',@organization_id,'17');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('169','59','ПОЖАРНЫЙ НА ПЕНСИИ',@organization_id,'17');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('168','57','ВЕТЕРАН ОРГАНОВ ВНУТРЕННИХ ДЕЛ',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('167','56','ИНВАЛИД ВОИНСКОЙ СЛУЖБЫ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('166','54','ЖЕНА/МУЖ ВОЕННОСЛУЖАЩЕГО, ПРОПАВШЕГО БЕЗ ВЕСТИ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('153','33','ЛИЦО (ЧАЭС) - 2 КАТЕГОРИЯ - ПОТЕРПЕВШИЙ',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('152','31','ЛИЦО (ЧАЭС) - 1 КАТЕГОРИЯ',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('151','30','ВОЕННОСЛУЖАЩИЙ СБУ НА ПЕНСИИ',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('138','7','РЕБЕНОК ВОЙНЫ',@organization_id,'34');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('137','6','ИНВАЛИД ВОЙНЫ ТРЕТЬЕЙ ГРУППЫ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('136','5','ИНВАЛИД ВОЙНЫ ВТОРОЙ ГРУППЫ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('135','4','ИНВАЛИД ВОЙНЫ ПЕРВОЙ ГРУППЫ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('134','3','ЧЛЕН СЕМЬИ ПОГИБШЕГО/УМЕРШЕГО ВЕТЕРАНА ВОЙНЫ',@organization_id,'21');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('133','2','УЧАСТНИК ВОЙНЫ',@organization_id,'10');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('132','1','УЧАСТНИК БОЕВЫХ ДЕЙСТВИЙ',@organization_id,'5');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('131','99','ПРИЕМНЫЕ СЕМЬИ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('130','96','ПРИЕМНЫЕ СЕМЬИ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('129','98','АВАРИЙНО-ДИСПЕТЧЕРСКАЯ СЛУЖБА',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('139','8','ЛИЦО С ОСОБЫМИ ЗАСЛУГАМИ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('140','9','РОДИТЕЛИ УМЕРШЕГО ЛИЦА С ОСОБЫМИ ЗАСЛУГАМИ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('149','26','НАЛОГОВЫЙ МИЛИЦИОНЕР НА ПЕНСИИ',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('150','29','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ СЕЛЬСКОГО НАЛОГОВОГО МИЛИЦИОНЕРА',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('148','25','СЛЕДОВАТЕЛЬ ПРОКУРАТУРЫ НА ПЕНСИИ',@organization_id,'18');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('147','24','СУДЬЯ В ОТСТАВКЕ',@organization_id,'12');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('146','23','СЕЛЬСКИЙ МЕДИК НА ПЕНСИИ',@organization_id,'44');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('145','20','СЕЛЬСКИЙ ПЕДАГОГ НА ПЕНСИИ',@organization_id,'40');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('144','13','РОДИТЕЛИ УМЕРШЕГО ЛИЦА С ОСОБЫМИ ТРУДОВЫМИ ЗАСЛУГАМИ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('143','12','ЛИЦО С ОСОБЫМИ ТРУДОВЫМИ ЗАСЛУГАМИ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('142','11','ВДОВА/ВДОВЕЦ ЛИЦА С ОСОБЫМИ ТРУДОВЫМИ ЗАСЛУГАМИ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('141','10','ВДОВА/ВДОВЕЦ ЛИЦА С ОСОБЫМИ ЗАСЛУГАМИ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('128','97','ДВОРНИКИ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('177','70','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(1)',@organization_id,'5');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('225','103','АФГАНИСТАН',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('212','62','ВДОВА/ВДОВЕЦ ВЕТЕРАНА ГОСУДАРСТВЕННОЙ ПОЖАРНОЙ ОХРАНЫ',@organization_id,'17');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('211','61','ВЕТЕРАН ГОСУДАРСТВЕННОЙ ПОЖАРНОЙ ОХРАНЫ',@organization_id,'17');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('210','58','ВДОВА/ВДОВЕЦ, ВЕТЕРАНА ОРГАНОВ ВНУТРЕННИХ ДЕЛ',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('209','55','РОДИТЕЛИ ПОГИБШЕГО ВОЕННОСЛУЖАЩЕГО',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('208','51','ЧЛЕН СЕМЬИ ВОЕННОСЛУЖАЩЕГО, ПОГИБШЕГО, УМЕРШЕГО, ПРОПАВШЕГО БЕЗ ВЕСТИ ИЛИ СТАВШЕГО ИНВАЛИДОМ',@organization_id,'21');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('207','50','ВДОВА/ВДОВЕЦ ВЕТЕРАНА ВОИНСКОЙ СЛУЖБЫ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('206','46','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО МИЛИЦИОНЕРА',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('205','45','МИЛИЦИОНЕР НА ПЕНСИИ',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('204','41','СОТРУДНИК УГОЛОВНО-ИСПОЛНИТЕЛЬНОЙ СИСТЕМЫ НА ПЕНСИИ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('203','40','ЛИЦО (ЧАЭС), РАБОТАВШЕЕ ЗА ПРЕДЕЛАМИ ЗОНЫ ОТЧУЖДЕНИЯ (ЛИКВИДАЦИЯ ПОСЛЕДСТВИЙ АВАРИИ)',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('213','75','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(4)',@organization_id,'20');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('214','80','ВЕТЕРАН ГОСУДАРСТВЕННОЙ СЛУЖБЫ СПЕЦ.СВЯЗИ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('224','19','ВЕТЕРАН ГОСУДАРСТВЕННОЙ КРИМ.-ИСПОЛНИТЕЛЬНОЙ СЛУЖБЫ',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('223','17','ЧЛЕН  МНОГОДЕТНОЙ СЕМЬИ',@organization_id,'22');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('222','16','МНОГОДЕТНЫЕ СЕМЬИ',@organization_id,'22');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('221','18','ВЕТЕРАН СЛУЖБЫ ГРАЖДАНСКОЙ ЗИЩИТЫ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('220','102','РАБОТНИКИ ХКП \"ГОРЭЛЕКТРОТРАНС\"',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('219','82','РОДИТЕЛИ И ЧЛЕНЫ СЕМЬИ ПОГИБШЕГО/УМЕРШЕГО СОТРУДНИКА ГОСУДАРСТВЕННОЙ СЛУЖБЫ СПЕЦ.СВЯЗИ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('218','90','ИНВАЛИДЫ 1 ГРУППЫ, ПОЛУЧАЮЩИЕ СОЦИАЛЬНУЮ ПЕНСИЮ ИЛИ ГОСУДАРСТВЕННУЮ ПОМОЩЬ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('217','94','ГРАЖДАНЕ, РЕАБИЛИТИРОВАННЫЕ СОГЛАСНО',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('216','95','СЕМЬИ ПОГИБШИХ (РЯДОВОЙ СОСТАВ) ПРИ ПРОХОЖДЕНИИ СРОЧНОЙ ВОИНСКОЙ СЛУЖБЫ, ИСПОЛНЯВШИХ СВОЙ ДОЛГ В МИ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('215','86','ДЕТИ-ИНВАЛИДЫ ДО 18 ЛЕТ, ГДЕ ОБА РОДИТЕЛИ ИНВАЛИДЫ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('202','37','РЕБЕНОК (ЧАЭС) УМЕРШЕГО ГРАЖДАНИНА',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('201','35','ЛИЦО (ЧАЭС) - 4 КАТЕГОРИЯ',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('200','32','ЛИЦО (ЧАЭС) - 2 КАТЕГОРИЯ - ЛИКВИДАТОР',@organization_id,'14');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('188','89','ДЕТИ-ИНВАЛИДЫ С ОНКОЛОГИЧЕСКИМИ ЗАБОЛЕВАНИЯМИ ДО 18 ЛЕТ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('187','88','МАТЕРИ-ОДИНОЧКИ (2 И БОЛЕЕ ДЕТЕЙ ДО 18 ЛЕТ)',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('186','87','МНОГОДЕТНЫЕ СЕМЬИ (3 И БОЛЕЕ ДЕТЕЙ ДО 18 ЛЕТ)',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('185','85','ДЕТИ-ИНВАЛИДЫ, ПРИКОВАННЫЕ К КРОВАТИ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('184','84','МАТЕРИ-ГЕРОИНИ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('183','83','РОДИТЕЛИ И ЧЛЕНЫ СЕМЬИ СОТРУДНИКА ГРАЖДАНСКОЙ ОБОРОНЫ, ПОГИБШЕГО, УМЕРШЕГО, ПРОПАВШЕГО БЕЗ ВЕСТИ ИЛИ',@organization_id,'15');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('182','81','ВДОВА/ВДОВЕЦ ВЕТЕРАНА ГОСУДАРСТВЕННОЙ СЛУЖБЫ СПЕЦ.СВЯЗИ',@organization_id,'16');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('181','74','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(3)',@organization_id,'13');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('180','73','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(2) - ИНВАЛИД 3 ГРУППЫ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('179','72','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(2) - ИНВАЛИД 2 ГРУППЫ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('178','71','ЖЕРТВА НАЦИСТСКИХ ПРЕСЛЕДОВАНИЙ, СТ. 6(2) - ИНВАЛИД 1 ГРУППЫ',@organization_id,'1');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('189','91','НЕРАБОТАЮЩИЕ РОДИТЕЛИ, ОСУЩЕСТВЛЯЮЩИЕ УХОД ЗА РЕБЕНКОМ-ИНВАЛИДОМ ДО 18 ЛЕТ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('190','92','ИНВАЛИДЫ 1, 2 ГРУППЫ ПО ЗРЕНИЮ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('199','28','СЕЛЬСКИЙ НАЛОГОВЫЙ МИЛИЦИОНЕР НА ПЕНСИИ',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('198','27','НЕТРУДОСПОСОБНЫЙ ЧЛЕН СЕМЬИ ПОГИБШЕГО НАЛОГОВОГО МИЛИЦИОНЕРА',@organization_id,'11');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('197','22','СЕЛЬСКИЙ СПЕЦИАЛИСТ ПО ЗАЩИТЕ РАСТЕНИЙ НА ПЕНСИИ',@organization_id,'45');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('196','21','СЕЛЬСКИЙ БИБЛИОТЕКАРЬ НА ПЕНСИИ',@organization_id,'41');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('195','99','ПРИЕМНЫЕ СЕМЬИ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('194','96','ПРИЕМНЫЕ СЕМЬИ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('193','101','УХОД ЗА ИНВАЛИДОМ 1 ГРУППЫ ВОВ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('192','100','СОЦИАЛЬНЫЕ РАБОЧИЕ',@organization_id,'50');
insert into `privilege_correction` (`id`, `object_id`, `correction`, `organization_id`, `organization_code`) values('191','93','СЕМЬИ ДЕТЕЙ ДО 18 ЛЕТ, БОЛЬНЫХ ДЦП',@organization_id,'50');
