//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 04:58:15 PM NOVST 
//


package org.complitex.osznconnection.file.service.file_description.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Formatters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Formatters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="date-pattern" type="{}DatePattern"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Formatters", propOrder = {
    "datePattern"
})
public class Formatters {

    @XmlElement(name = "date-pattern", required = true)
    protected DatePattern datePattern;

    /**
     * Gets the value of the datePattern property.
     * 
     * @return
     *     possible object is
     *     {@link DatePattern }
     *     
     */
    public DatePattern getDatePattern() {
        return datePattern;
    }

    /**
     * Sets the value of the datePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatePattern }
     *     
     */
    public void setDatePattern(DatePattern value) {
        this.datePattern = value;
    }

}
