-- --------------------------------
-- Current database version
-- --------------------------------
INSERT INTO `update` (`version`) VALUE ('20131224_922_0.2.11');

ALTER TABLE `payment`
  MODIFY `OWN_NUM` VARCHAR(15) COMMENT 'Номер дела',
  MODIFY `REE_NUM` INTEGER(2) COMMENT 'Номер реестра',
  MODIFY `OPP` VARCHAR(8) COMMENT 'Признаки наличия услуг',
  MODIFY `NUMB` INTEGER(2) COMMENT 'Общее число зарегистрированных',
  MODIFY `MARK` INTEGER(2) COMMENT 'К-во людей, которые пользуются льготами',
  MODIFY `CODE` INTEGER(4) COMMENT 'Код ЖЭО',
  MODIFY `ENT_COD` INTEGER(10) COMMENT 'Код ЖЭО ОКПО',
  MODIFY `FROG`  DECIMAL(5,1) COMMENT 'Процент льгот',
  MODIFY `FL_PAY` DECIMAL(9,2) COMMENT 'Общая плата',
  MODIFY `NM_PAY` DECIMAL(9,2) COMMENT 'Плата в пределах норм потребления',
  MODIFY `DEBT` DECIMAL(9,2) COMMENT 'Сумма долга',
  MODIFY `CODE2_1` INTEGER(6) COMMENT 'Оплата жилья',
  MODIFY `CODE2_2` INTEGER(6) COMMENT 'система',
  MODIFY `CODE2_3` INTEGER(6) COMMENT 'Горячее водоснабжение',
  MODIFY `CODE2_4` INTEGER(6) COMMENT 'Холодное водоснабжение',
  MODIFY `CODE2_5` INTEGER(6) COMMENT 'Газоснабжение',
  MODIFY `CODE2_6` INTEGER(6) COMMENT 'Электроэнергия',
  MODIFY `CODE2_7` INTEGER(6) COMMENT 'Вывоз мусора',
  MODIFY `CODE2_8` INTEGER(6) COMMENT 'Водоотведение',
  MODIFY `NORM_F_1` DECIMAL(10,4) COMMENT 'Общая площадь (оплата жилья)',
  MODIFY `NORM_F_2` DECIMAL(10,4) COMMENT 'Объемы потребления (отопление)',
  MODIFY `NORM_F_3` DECIMAL(10,4) COMMENT 'Объемы потребления (горячего водо.)',
  MODIFY `NORM_F_4` DECIMAL(10,4) COMMENT 'Объемы потребления (холодное водо.)',
  MODIFY `NORM_F_5` DECIMAL(10,4) COMMENT 'Объемы потребления (газоснабжение)',
  MODIFY `NORM_F_6` DECIMAL(10,4) COMMENT 'Объемы потребления (электроэнергия)',
  MODIFY `NORM_F_7` DECIMAL(10,4) COMMENT 'Объемы потребления (вывоз мусора)',
  MODIFY `NORM_F_8` DECIMAL(10,4) COMMENT 'Объемы потребления (водоотведение)',
  MODIFY `OWN_NUM_SR` VARCHAR(15) COMMENT 'Лицевой счет в обслуж. организации',
  MODIFY `DAT1` DATE COMMENT 'Дата начала действия субсидии',
  MODIFY `DAT2` DATE COMMENT 'Дата формирования запроса',
  MODIFY `OZN_PRZ` INTEGER(1) COMMENT 'Признак (0 - автоматическое назначение, 1-для ручного расчета)',
  MODIFY `DAT_F_1` DATE COMMENT 'Дата начала для факта',
  MODIFY `DAT_F_2` DATE COMMENT 'Дата конца для факта',
  MODIFY `DAT_FOP_1` DATE COMMENT 'Дата начала для факта отопления',
  MODIFY `DAT_FOP_2` DATE COMMENT 'Дата конца для факта отопления',
  MODIFY `ID_RAJ` VARCHAR(5) COMMENT 'Код района',
  MODIFY `SUR_NAM` VARCHAR(30) COMMENT 'Фамилия',
  MODIFY `F_NAM` VARCHAR(15) COMMENT 'Имя',
  MODIFY `M_NAM` VARCHAR(20) COMMENT 'Отчество',
  MODIFY `IND_COD` VARCHAR(10) COMMENT 'Идентификационный номер',
  MODIFY `INDX` VARCHAR(6) COMMENT 'Индекс почтового отделения',
  MODIFY `N_NAME` VARCHAR(30) COMMENT 'Название населенного пункта',
  MODIFY `VUL_NAME` VARCHAR(30) COMMENT 'Название улицы',
  MODIFY `BLD_NUM` VARCHAR(7) COMMENT 'Номер дома',
  MODIFY `CORP_NUM` VARCHAR(2) COMMENT 'Номер корпуса',
  MODIFY `FLAT` VARCHAR(9) COMMENT 'Номер квартиры',
  MODIFY `CODE3_1` INTEGER(6) COMMENT 'Код тарифа оплаты жилья',
  MODIFY `CODE3_2` INTEGER(6) COMMENT 'Код тарифа отопления',
  MODIFY `CODE3_3` INTEGER(6) COMMENT 'Код тарифа горячего водоснабжения',
  MODIFY `CODE3_4` INTEGER(6) COMMENT 'Код тарифа холодного водоснабжения',
  MODIFY `CODE3_5` INTEGER(6) COMMENT 'Код тарифа - газоснабжение',
  MODIFY `CODE3_6` INTEGER(6) COMMENT 'Код тарифа-электроэнергии',
  MODIFY `CODE3_7` INTEGER(6) COMMENT 'Код тарифа - вывоз мусора',
  MODIFY `CODE3_8` INTEGER(6) COMMENT 'Код тарифа - водоотведение',
  MODIFY `OPP_SERV` VARCHAR(8) COMMENT 'Резерв',
  MODIFY `RESERV1` INTEGER(10) COMMENT 'Резерв',
  MODIFY `RESERV2` VARCHAR(10) COMMENT 'Резер';

ALTER TABLE `benefit`
  MODIFY `OWN_NUM` VARCHAR(15) COMMENT 'Номер дела',
  MODIFY `REE_NUM` INTEGER(2) COMMENT 'Номер реестра',
  MODIFY `OWN_NUM_SR` VARCHAR(15) COMMENT 'Лицевой счет в обслуж. организации',
  MODIFY `FAM_NUM` INTEGER(2) COMMENT 'Номер члена семьи',
  MODIFY `SUR_NAM` VARCHAR(30) COMMENT 'Фамилия',
  MODIFY `F_NAM` VARCHAR(15) COMMENT 'Имя',
  MODIFY `M_NAM` VARCHAR(20) COMMENT 'Отчество',
  MODIFY `IND_COD` VARCHAR(10) COMMENT 'Идентификационный номер',
  MODIFY `PSP_SER` VARCHAR(6) COMMENT 'Серия паспорта',
  MODIFY `PSP_NUM` VARCHAR(6) COMMENT 'Номер паспорта',
  MODIFY `OZN` INTEGER(1) COMMENT 'Признак владельца',
  MODIFY `CM_AREA` DECIMAL(10,2) COMMENT 'Общая площадь',
  MODIFY `HEAT_AREA` DECIMAL(10,2) COMMENT 'Обогреваемая площадь',
  MODIFY `OWN_FRM` INTEGER(6) COMMENT 'Форма собственности',
  MODIFY `HOSTEL` INTEGER(2) COMMENT 'Количество комнат',
  MODIFY `PRIV_CAT` INTEGER(3) COMMENT 'Категория льготы на платежи',
  MODIFY `ORD_FAM` INTEGER(2) COMMENT 'Порядок семьи льготников для расчета платежей',
  MODIFY `OZN_SQ_ADD` INTEGER(1) COMMENT 'Признак учета дополнительной площади',
  MODIFY `OZN_ABS` INTEGER(1) COMMENT 'Признак отсутствия данных в базе ЖЭО',
  MODIFY `RESERV1` DECIMAL(10,2) COMMENT 'Резерв',
  MODIFY `RESERV2` VARCHAR(10) COMMENT 'Резерв';

ALTER TABLE `subsidy_tarif`
  MODIFY `T11_DATA_T` VARCHAR(10) COMMENT '',
  MODIFY `T11_DATA_E` VARCHAR(10) COMMENT '',
  MODIFY `T11_DATA_R` VARCHAR(10) COMMENT '',
  MODIFY `T11_MARK` INTEGER(3) COMMENT '',
  MODIFY `T11_TARN` INTEGER(6) COMMENT '',
  MODIFY `T11_CODE1` INTEGER(3) COMMENT '',
  MODIFY `T11_CODE2` INTEGER(6) COMMENT '',
  MODIFY `T11_COD_NA` VARCHAR(40) COMMENT '',
  MODIFY `T11_CODE3` INTEGER(6) COMMENT '',
  MODIFY `T11_NORM_U` DECIMAL(19, 10) COMMENT '',
  MODIFY `T11_NOR_US` DECIMAL(19, 10) COMMENT '',
  MODIFY `T11_CODE_N` INTEGER(3) COMMENT '',
  MODIFY `T11_COD_ND` INTEGER(3) COMMENT '',
  MODIFY `T11_CD_UNI` INTEGER(3) COMMENT '',
  MODIFY `T11_CS_UNI` DECIMAL (19, 10) COMMENT '',
  MODIFY `T11_NORM` DECIMAL (19, 10) COMMENT '',
  MODIFY `T11_NRM_DO` DECIMAL (19, 10) COMMENT '',
  MODIFY `T11_NRM_MA` DECIMAL (19, 10) COMMENT '',
  MODIFY `T11_K_NADL` DECIMAL (19, 10) COMMENT '';

ALTER TABLE `actual_payment`
  MODIFY `SUR_NAM` VARCHAR(30) COMMENT 'Фамилия',
  MODIFY `F_NAM` VARCHAR(15) COMMENT 'Имя',
  MODIFY `M_NAM` VARCHAR(20) COMMENT 'Отчество',
  MODIFY `INDX` VARCHAR(6) COMMENT 'Индекс почтового отделения',
  MODIFY `N_NAME` VARCHAR(30) COMMENT 'Название населенного пункта',
  MODIFY `N_CODE` VARCHAR(5) COMMENT '',
  MODIFY `VUL_CAT` VARCHAR(7) COMMENT 'Тип улицы',
  MODIFY `VUL_NAME` VARCHAR(30) COMMENT 'Название улицы',
  MODIFY `VUL_CODE` VARCHAR(5) COMMENT 'Код улицы',
  MODIFY `BLD_NUM` VARCHAR(7) COMMENT 'Номер дома',
  MODIFY `CORP_NUM` VARCHAR(2) COMMENT 'Номер корпуса',
  MODIFY `FLAT` VARCHAR(9) COMMENT 'Номер квартиры',
  MODIFY `OWN_NUM` VARCHAR (15) COMMENT 'Номер дела',
  MODIFY `APP_NUM` VARCHAR(8) COMMENT '',
  MODIFY `DAT_BEG` DATE COMMENT '',
  MODIFY `DAT_END` DATE COMMENT '',
  MODIFY `CM_AREA` DECIMAL(7,2) COMMENT '',
  MODIFY `NM_AREA` DECIMAL(7,2) COMMENT '',
  MODIFY `BLC_AREA` DECIMAL(5,2) COMMENT '',
  MODIFY `FROG` DECIMAL(5,1) COMMENT '',
  MODIFY `DEBT` DECIMAL(10,2) COMMENT '',
  MODIFY `NUMB` INTEGER(2) COMMENT '',
  MODIFY `P1` DECIMAL(10,4) COMMENT 'фактическое начисление',
  MODIFY `N1` DECIMAL(10,4) COMMENT 'фактический тариф',
  MODIFY `P2` DECIMAL(10,4) COMMENT '',
  MODIFY `N2` DECIMAL(10,4) COMMENT '',
  MODIFY `P3` DECIMAL(10,4) COMMENT '',
  MODIFY `N3` DECIMAL(10,4) COMMENT '',
  MODIFY `P4` DECIMAL(10,4) COMMENT '',
  MODIFY `N4` DECIMAL(10,4) COMMENT '',
  MODIFY `P5` DECIMAL(10,4) COMMENT '',
  MODIFY `N5` DECIMAL(10,4) COMMENT '',
  MODIFY `P6` DECIMAL(10,4) COMMENT '',
  MODIFY `N6` DECIMAL(10,4) COMMENT '',
  MODIFY `P7` DECIMAL(10,4) COMMENT '',
  MODIFY `N7` DECIMAL(10,4) COMMENT '',
  MODIFY `P8` DECIMAL(10,4) COMMENT '',
  MODIFY `N8` DECIMAL(10,4) COMMENT '';

ALTER TABLE `subsidy`
  MODIFY `FIO` VARCHAR(30) COMMENT 'ФИО',
  MODIFY `ID_RAJ` VARCHAR(5) COMMENT 'Код района',
  MODIFY `NP_CODE` VARCHAR(5) COMMENT 'Код населенного пункта',
  MODIFY `NP_NAME`VARCHAR(30) COMMENT 'Название населенного пункта',
  MODIFY `CAT_V` VARCHAR(7) COMMENT 'Тип улицы',
  MODIFY `VULCOD` VARCHAR(8) COMMENT 'Код улицы',
  MODIFY `NAME_V` VARCHAR(30) COMMENT 'Название улицы',
  MODIFY `BLD` VARCHAR(7) COMMENT 'Номер дома',
  MODIFY `CORP` VARCHAR(2) COMMENT 'Номер корпуса',
  MODIFY `FLAT` VARCHAR(9) COMMENT 'Номер квартиры',
  MODIFY `RASH` VARCHAR(15) COMMENT 'Номер л/с ПУ',
  MODIFY `NUMB` VARCHAR(8) COMMENT '',
  MODIFY `DAT1` DATE COMMENT 'Дата начала периода, на который предоставляется субсидия',
  MODIFY `DAT2` DATE COMMENT 'Дата конца периода, на который предоставляется субсидия',
  MODIFY `NM_PAY` DECIMAL(9,2) COMMENT 'Начисление в пределах нормы',

  MODIFY `P1` DECIMAL(9,4) COMMENT '',
  MODIFY `P2` DECIMAL(9,4) COMMENT '',
  MODIFY `P3` DECIMAL(9,4) COMMENT '',
  MODIFY `P4` DECIMAL(9,4) COMMENT '',
  MODIFY `P5` DECIMAL(9,4) COMMENT '',
  MODIFY `P6` DECIMAL(9,4) COMMENT '',
  MODIFY `P7` DECIMAL(9,4) COMMENT '',
  MODIFY `P8` DECIMAL(9,4) COMMENT '',

  MODIFY `SM1` DECIMAL(9,2) COMMENT '',
  MODIFY `SM2` DECIMAL(9,2) COMMENT '',
  MODIFY `SM3` DECIMAL(9,2) COMMENT '',
  MODIFY `SM4` DECIMAL(9,2) COMMENT '',
  MODIFY `SM5` DECIMAL(9,2) COMMENT '',
  MODIFY `SM6` DECIMAL(9,2) COMMENT '',
  MODIFY `SM7` DECIMAL(9,2) COMMENT '',
  MODIFY `SM8` DECIMAL(9,2) COMMENT '',

  MODIFY `SB1` DECIMAL(9,2) COMMENT '',
  MODIFY `SB2` DECIMAL(9,2) COMMENT '',
  MODIFY `SB3` DECIMAL(9,2) COMMENT '',
  MODIFY `SB4` DECIMAL(9,2) COMMENT '',
  MODIFY `SB5` DECIMAL(9,2) COMMENT '',
  MODIFY `SB6` DECIMAL(9,2) COMMENT '',
  MODIFY `SB7` DECIMAL(9,2) COMMENT '',
  MODIFY `SB8` DECIMAL(9,2) COMMENT '',

  MODIFY `OB1` DECIMAL(9,2) COMMENT '',
  MODIFY `OB2` DECIMAL(9,2) COMMENT '',
  MODIFY `OB3` DECIMAL(9,2) COMMENT '',
  MODIFY `OB4` DECIMAL(9,2) COMMENT '',
  MODIFY `OB5` DECIMAL(9,2) COMMENT '',
  MODIFY `OB6` DECIMAL(9,2) COMMENT '',
  MODIFY `OB7` DECIMAL(9,2) COMMENT '',
  MODIFY `OB8` DECIMAL(9,2) COMMENT '',

  MODIFY `SUMMA` DECIMAL(13,2) COMMENT '',
  MODIFY `NUMM` INTEGER(2) COMMENT '',
  MODIFY `SUBS` DECIMAL(13,2) COMMENT '',
  MODIFY `KVT` INTEGER(3) COMMENT '';
