SET @organization_id = 1;

insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('1','Учасники бойових дiй',@organization_id,'5');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('2','Учасники вiйни',@organization_id,'10');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('3','сiм\'я загиблого',@organization_id,'21');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('4','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('5','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('6','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('7','дiти вiйни',@organization_id,'34');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('8','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('9','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('10','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('11','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('12','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('13','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('16','багатодiтна сiм`я (Новий закон',@organization_id,'22');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('17','багатодiтна сiм`я (Новий закон',@organization_id,'22');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('18','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('19','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('20','Педагог, село(смт)',@organization_id,'40');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('21','культ-просв працiвн, село(смт)',@organization_id,'41');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('22','ветеринарнi працiвн, село(смт)',@organization_id,'45');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('23','мед.працiвники, село(смт)',@organization_id,'44');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('24','Суддi',@organization_id,'12');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('25','Слiдчi прокуратури',@organization_id,'18');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('26','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('27','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('28','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('29','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('30','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('31','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('32','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('33','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('34','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('35','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('36','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('37','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('38','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('39','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('40','Чорнобильцi 1,2 категорiї',@organization_id,'14');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('41','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('42','Слiдчi прокуратури',@organization_id,'18');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('43','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('44','сiм\'я загиблого',@organization_id,'21');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('45','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('46','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('47','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('48','сiм\'я загиблого',@organization_id,'21');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('49','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('50','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('51','сiм\'я загиблого',@organization_id,'21');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('52','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('53','Вiйськовослужбовцi',@organization_id,'15');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('54','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('55','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('56','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('57','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('58','Спiвробiтники мiлiцiї',@organization_id,'11');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('59','Працiвники пожежної охорони',@organization_id,'17');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('60','Працiвники пожежної охорони',@organization_id,'17');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('61','Працiвники пожежної охорони',@organization_id,'17');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('62','Працiвники пожежної охорони',@organization_id,'17');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('63','Реабiлiтованi (iнв-ди,пенс-ри)',@organization_id,'13');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('65','iнвалiди по зору',@organization_id,'31');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('66','iнвалiди по зору',@organization_id,'31');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('67','Iнвалiди 1-ї групи (непрац.)',@organization_id,'2');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('68','Iнвалiди 1-ї групи (непрац.)',@organization_id,'2');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('69','Iнвалiди 1-ї групи (непрац.)',@organization_id,'2');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('70','Учасники бойових дiй',@organization_id,'5');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('71','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('72','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('73','Iнвалiди вiйни',@organization_id,'1');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('74','Реабiлiтованi (iнв-ди,пенс-ри)',@organization_id,'13');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('75','вдова iнвалiда вiйни',@organization_id,'20');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('80','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('81','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('82','Ветерани вiйськової служби',@organization_id,'16');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('83','Вiйськовослужбовцi',@organization_id,'15');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('84','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('85','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('86','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('87','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('88','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('89','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('90','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('91','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('92','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('93','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('94','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('95','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('96','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('97','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('98','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('99','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('100','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('101','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('102','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('103','мiсцевi пiльги',@organization_id,'50');
insert into `privilege_correction` (`object_id`, `correction`, `organization_id`, `organization_code`) values('104','мiсцевi пiльги',@organization_id,'50');
